### ISSUE TITLE
Colour-code nicknames

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/Quaternion#286]

**Comment by Quiark** [comment]
see for reference https://github.com/Quiark/tensor/blob/master/client/qml/jschat.js#L33 but it could use some improvement

What I expect from nickname colouring is to keep them stable so that I can remember people by their colour. But that poses a problem if the colouring algo needs to avoid background colour.

**Comment by KitsuneRal** [comment]
Requirements as I see them are:
- should not blend in the background colour (I think it should be fine if the whole palette changes if the background colour changes - otherwise it's a lost battle)
- should be stable per-user (I wouldn't even change the colour when a user changes the display name) - maybe base calculation on user ID

**Comment by KitsuneRal** [comment]
And I actually briefly looked at Tensor code before but my understanding is that this algorithm doesn't protect from colours with similar hue+saturation and doesn't take the background colour into account. So I'd like to have something better for Quaternion (with possible reuse in Tensor).

**Comment by rpallai** [comment]
@KitsuneRal it's resolved by now, isn't it?

**Comment by KitsuneRal** [comment]
Thanks for the heads up. It certainly is, fulfilling the two mentioned requirements, as per #528.
