### ISSUE TITLE
Bad scaling on icons and text

### ISSUE THREAD

**Issue by 2xsaiko** [quotient-im/Quaternion#649]
### Description

The font in the chat UI is rendered (supposedly) at 1x scale and pixelated. All icons are also pixelated.

### Steps to reproduce

- Use KDE on a 4k monitor with global scale set to 1.5x

![](https://i.imgur.com/SbHkO9M.png)

### Version information

- **Quaternion version**: 0.0.9.4b
- **Qt version**: 5.13.2
- **Install method**: AUR
- **Platform**: Arch Linux x64, Plasma Desktop

**Comment by therealfarfetchd** [comment]
Setting `UI/Fonts/render_type` to QtRendering seems to fix the font issue. Icons are still pixelated though.

**Comment by KitsuneRal** [comment]
Sorry - this got lost in the traffic and I just found it. Is that on X or Wayland? X is known to be bad at handling fractional scale factors. Also, high DPI scaling on Qt only got reasonable support for fractional scale factors [since Qt 5.14](https://doc-snapshots.qt.io/qt5-5.15/highdpi.html). If you're still around, can you try it with Qt 5.14 or later?

**Comment by 2xsaiko** [comment]
That was on X. With Qt 5.15.2, the text looks fine although icons (like the close/detach icons on the panels in the screenshot above, or menu icons) are still pixelated. That should be able to be fixed like [here][1] though, I think.

[1]: https://github.com/keepassxreboot/keepassxc/pull/3332

**Comment by KitsuneRal** [comment]
Aha, thanks, I didn't know about that attribute.

**Comment by KitsuneRal** [comment]
Turned out things are a bit worse: icon dimensions in those places were hardcoded to 16 :-\
