### ISSUE TITLE
Missing/wrong minimum macOS version in generated bundle

### ISSUE THREAD

**Issue by csnover** [quotient-im/Quaternion#764]
### Description

The release app bundle generated by CI sets the minimum macOS version to 10.15, even though it bundles a version of Qt that supports 10.13 and later. It should probably be compiled with `-mmacosx-version-min=10.13` / with the environment variable `QMAKE_MACOSX_DEPLOYMENT_TARGET=10.13`.

### Steps to reproduce

- Download bundle on a machine running macOS prior to 10.15
- Try running the app

Expected: Runs successfully
Actual: Error “You can’t use this version of the application “quaternion.app” with this version of macOS. You have macOS 10.14.6. The application requires macOS 10.15 or later.”

Bypassing the OS check by running `quaternion.app/Contents/MacOS/quaternion` directly from the command line works fine.

### Version information

- **Quaternion version**: 0.0.95-beta4
- **Qt version**: 5.14.2
- **Install method**: Download from GitHub releases
- **Platform**: macOS 10.14.6

**Comment by KitsuneRal** [comment]
@aaronraimist could you look at that? I believe that the corresponding CMake variable should be `MACOSX_DEPLOYMENT_TARGET` - let me know if I got it right. Also - would it be better to pass this variable in CI only or put it right to `CMakeLists.txt` so that even builders from source could benefit from it (those normally run the binary on the same machine they compile though)?
