### ISSUE TITLE
Open external link: Missing link address

### ISSUE THREAD

**Issue by sdicke** [quotient-im/Quaternion#820]
### Description

When opening a Matrix-external link, there is a dialog displayed. At most in the German translation of the GUI, there is displayed „% 1“ instead of a URI.

### Steps to reproduce

- Click on a link addressing addressing a URI not associated with a Matrix resource.
- A dialog request the permission to open the link in an external application which does not contain the link get displayed.

I would expect that such kind of dialogs would display the address of the resource to open in the external application.

The following was logged (the actual link is replaced with $$$):

QString::arg: Argument missing: Eine externe Anwendung wird geöffnet, um einen Nicht-Matrix-Link zu besuchen: 

 % 1 

 Ist das richtig?, $$$
quotient.jobs: 200 <- GET $$$

### Version information

- **Quaternion version**: v0.0.95.1
- **Qt version**:  5.15.2.
- **Install method**: zypper: packages matrix-quaternion and matrix-quaternion-lang
- **Platform**: openSUSE Tumbleweed

**Comment by KitsuneRal** [comment]
Thanks for reporting. Right, there's a typo in the German translation - it has an extra whitespace between `%` and `1`, thereby breaking the `%1` placeholder that would normally be replaced with the URL. It is already fixed in the translation management system and is pending an (overdue) export to the source code.

**Comment by KitsuneRal** [comment]
This is fixed in 0.0.96 beta.
