### ISSUE TITLE
Fail to start on Wayland

### ISSUE THREAD

**Issue by mizzunet** [quotient-im/Quaternion#826]
### Description

App fails to start on RiverWM which is a wayland compositor.

### Steps to reproduce

- Download https://github.com/quotient-im/Quaternion/releases/download/0.0.95.1/quaternion-0.0.95.1.AppImage
- chmod +x it
- Try to run in, `./quaternion-0.0.95.1.AppImage`

Describe how what happens differs from what you expected.
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

* Starts fine by `QT_QPA_PLATFORM=xcb ./quaternion-0.0.95.1.AppImage`
* I have `qt5-wayland` package already been installed
### Version information

- **Quaternion version**:0.0.95.1
- **Qt version**:  `qt5-base 5.15.4+kde+r146-1`
- **Install method**:  AppImage from releases
- **Platform**:  ArchLinux

**Comment by mizzunet** [comment]
Then I built from source, it works now

**Comment by KitsuneRal** [comment]
AppImage is generally not a good match for distros running on the forefront of evolution, like Arch. Because it packages quite a few libraries along with the application, this may lead to functionality of applications and integration with the desktop being limited and in some cases downright broken: in your particular case, AppImage uses Qt packaged along with Quaternion, not the one installed on your system.

That said, Quaternion is not quite ready for native use on Wayland - it starts but some parts of the UI (menus, in particular) may not show up in some environments. Things should improve once Quaternion moves over to Qt 6, likely sometime next year.
