### ISSUE TITLE
Feature request: Gtk theme or DE theme

### ISSUE THREAD

**Issue by narcisgarcia** [quotient-im/Quaternion#841]
- Debian GNU/Linux 11/Stable (amd64) +Gnome
- Quaternion from OS package 0.0.9.5~beta2-2

My request is to get environment's theme colors and apply them to application, same as other non-Gtk applications do.

**Comment by KitsuneRal** [comment]
This is working as expected on my Fedora machine here (with the latest version, 0.0.95.1 - but the relevant things are entirely due to Qt, there's nothing specific to Quaternion here; and it's been like this since forever). I think you should have `qgnomeplatfrom-qt5` installed for the integration to work, but that's pretty much it.

**Comment by narcisgarcia** [comment]
No "gnome...qt" package at Debian/Stable repositories.

**Comment by KitsuneRal** [comment]
Well, I don't know how other non-Gtk applications do it on your machine. You can try your chances with the [Qt port of Adwaita](https://packages.debian.org/bullseye/adwaita-qt), [qt5ct](https://packages.debian.org/bullseye/qt5ct) and [Kvantum](https://packages.debian.org/bullseye/qt5-style-kvantum). That's all I can help with. Quaternion doesn't do any theming, it only uses the looks Qt provides.
